version: "3.9"
services:
  dev_app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_NAME=Blog Application
