FROM node:lts-alpine3.14
LABEL maintainer="muteshi.com"

WORKDIR /app

RUN npm install --global pm2

# Install dependencies
COPY package*.json .

RUN npm install --production

# Setup directory structure
COPY . .
RUN npm run build
EXPOSE 3000

USER node

CMD [ "pm2-runtime", "npm", "--", "start" ]