FROM node:lts-alpine3.14
LABEL maintainer="muteshi.com"

WORKDIR /app
# Install dependencies
COPY package.json .

RUN npm install

# Setup directory structure
COPY . .
RUN npm run build
EXPOSE 3000

CMD [ "npm","run","dev" ]