version: "3.9"
services:
  blog_app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes:
      - .:/app
    environment:
      - REACT_APP_NAME=Blog Application
  nginx:
    restart: unless-stopped
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - certbot-conf:/etc/nginx/ssl/:ro
      - nginx-data:/etc/nginx/conf.d/:rw
      - certbot-www:/var/www/certbot/:ro
  certbot:
    image: certbot/certbot:latest
    restart: unless-stopped
    volumes:
      - certbot-www:/var/www/certbot/:rw
      - certbot-conf:/etc/letsencrypt/:rw

volumes:
  certbot-www:
  certbot-conf:
  nginx-data:
