FROM node:lts-alpine3.14
LABEL maintainer="muteshi.com"

RUN npm install --global pm2

# Install dependencies
COPY package*.json ./

RUN npm install 

# Setup directory structure
WORKDIR /app
EXPOSE 3000

COPY . .
RUN npm run build

USER node

CMD [ "pm2-runtime", "npm", "--", "start" ]